### PR TITLE
Support for multimple monitors

### PR DESCRIPTION
**Pull request by mrowqa**
Hi,

thanks for the tool. I thought about writing such a thing myself, but eventually I landed here. Here is some contribution of mine that adds support for multiple monitors.

Regards,
mrowqa

### CODE REVIEW

**Comment by mrowqa** [comment]
Solves #11.

**Comment by Ortega-Dan** [comment]
Hey @taviso , Looks like this contribution is nice. Please merge it into main. This project is great. And this pull request will make it better.

**Comment by taviso** [comment]
Thanks! Sorry for the slow response, the patch does indeed look good.

I'm just thinking about how to make it optional, i.e. if I only want it on one monitor. I like that there are no configuration files or registry keys, so I think maybe it should be an `#ifdef`. hmmm..

**Comment by mrowqa** [comment]
> if I only want it on one monitor

Assuming it's just an example, does anyone actually want such a behavior? As far as I remember, on gnome shell the corners work on all screens.

You can also try changing `MAX_MONITORS` to 1 and see how it behaves. Hopefully, it iterates over monitors in the same order.

**Comment by Ortega-Dan** [comment]
> > if I only want it on one monitor
> 
> Assuming it's just an example, does anyone actually want such a behavior? As far as I remember, on gnome shell the corners work on all screens.
> 
> You can also try changing `MAX_MONITORS` to 1 and see how it behaves. Hopefully, it iterates over monitors in the same order.

Yeap, it works on all screens on Gnome 3.

**Comment by gitguys** [comment]
Is there a pre-compiled binary available for download that works on all connected monitors?

**Comment by mrowqa** [comment]
@gitguys I decided not to provide any binaries since building it is quick and simple and I adjusted the constants & hotkey locally for my personal usage.

**Comment by Ortega-Dan** [comment]
@gitguys I actually have a precompiled .exe that I deploy to my windows machines ... I've had it there for more than one year ... (as you can see from the last commits in there)
You can check it out here .. [withSuperEasyInstallInstructions](https://github.com/Ortega-Dan/hotcorner/tree/master/Compiled)

That was thanks to @mrowqa changes .. (his name is in my version of the README)

**Pull request closed without merging**
